alter table public.meta_purchase_attempts
  add column if not exists request_sent_at timestamptz,
  add column if not exists completed_at timestamptz,
  add column if not exists accepted boolean;

create table if not exists public.meta_purchase_browser_calls (
  id bigint generated by default as identity primary key,
  order_number text not null references public.orders(order_number) on delete cascade,
  event_id text not null,
  attempted_at timestamptz not null default now(),
  dispatched boolean not null default true,
  constraint meta_purchase_browser_calls_event_id_matches_order
    check (event_id = order_number)
);

create index if not exists meta_purchase_browser_calls_order_number_idx
  on public.meta_purchase_browser_calls (order_number, attempted_at desc);

alter table public.meta_purchase_browser_calls enable row level security;

revoke all on table public.meta_purchase_browser_calls from public, anon, authenticated;
grant insert on table public.meta_purchase_browser_calls to service_role;

create or replace function public.record_meta_purchase_browser_call(
  p_order_number text,
  p_event_id text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_order_number is null or p_event_id is null or p_event_id <> p_order_number then
    raise exception 'invalid_meta_purchase_browser_event';
  end if;

  insert into public.meta_purchase_browser_calls (order_number, event_id)
  values (p_order_number, p_event_id);
end;
$$;

create or replace function public.mark_meta_purchase_delivery_sent(
  p_order_id uuid,
  p_event_id text,
  p_meta_response_status integer default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.orders
  set meta_purchase_status = 'sent',
      updated_at = now()
  where id = p_order_id
    and order_number = p_event_id
    and meta_purchase_status = 'pending';

  update public.meta_purchase_attempts
  set status = 'sent',
      meta_response_status = p_meta_response_status,
      completed_at = now(),
      accepted = p_meta_response_status between 200 and 299
  where order_id = p_order_id
    and event_id = p_event_id
    and status = 'claimed';
end;
$$;

create or replace function public.record_meta_purchase_delivery_result(
  p_order_id uuid,
  p_event_id text,
  p_status text,
  p_meta_response_status integer default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_status not in ('failed', 'skipped') then
    raise exception 'invalid_meta_purchase_delivery_status';
  end if;

  update public.meta_purchase_attempts
  set status = p_status,
      meta_response_status = p_meta_response_status,
      completed_at = now(),
      accepted = false
  where order_id = p_order_id
    and event_id = p_event_id
    and status = 'claimed';
end;
$$;

revoke all on function public.record_meta_purchase_browser_call(text, text) from public, anon, authenticated;
grant execute on function public.record_meta_purchase_browser_call(text, text) to service_role;

revoke all on function public.mark_meta_purchase_delivery_sent(uuid, text, integer) from public, anon, authenticated;
revoke all on function public.record_meta_purchase_delivery_result(uuid, text, text, integer) from public, anon, authenticated;

grant execute on function public.mark_meta_purchase_delivery_sent(uuid, text, integer) to service_role;
grant execute on function public.record_meta_purchase_delivery_result(uuid, text, text, integer) to service_role;