alter table public.orders
  add column if not exists meta_purchase_status text check (meta_purchase_status in ('pending', 'sent'));

create table if not exists public.meta_purchase_attempts (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  order_number text not null,
  event_id text not null,
  attempt_number integer not null check (attempt_number > 0),
  status text not null check (status in ('claimed', 'sent', 'failed', 'skipped')),
  attempted_at timestamptz not null default now(),
  meta_response_status integer,
  unique (order_id, attempt_number)
);

create index if not exists meta_purchase_attempts_order_id_idx
  on public.meta_purchase_attempts (order_id, attempted_at desc);

create or replace function public.claim_meta_purchase_delivery(
  p_order_id uuid,
  p_event_id text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare v_claimed boolean; v_order_number text;
begin
  update public.orders
  set meta_purchase_status = 'pending',
      updated_at = now()
  where id = p_order_id
    and order_number = p_event_id
    and meta_purchase_status is null
  returning true, order_number into v_claimed, v_order_number;

  if v_claimed then
    insert into public.meta_purchase_attempts (order_id, order_number, event_id, attempt_number, status)
    values (
      p_order_id,
      v_order_number,
      p_event_id,
      (select count(*)::integer + 1 from public.meta_purchase_attempts where order_id = p_order_id),
      'claimed'
    );
  end if;

  return coalesce(v_claimed, false);
end;
$$;

create or replace function public.mark_meta_purchase_delivery_sent(
  p_order_id uuid,
  p_event_id text,
  p_meta_response_status integer default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.orders
  set meta_purchase_status = 'sent',
      updated_at = now()
  where id = p_order_id
    and order_number = p_event_id
    and meta_purchase_status = 'pending';

  update public.meta_purchase_attempts
  set status = 'sent',
      meta_response_status = p_meta_response_status
  where order_id = p_order_id
    and event_id = p_event_id
    and status = 'claimed';
end;
$$;

create or replace function public.record_meta_purchase_delivery_result(
  p_order_id uuid,
  p_event_id text,
  p_status text,
  p_meta_response_status integer default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_status not in ('failed', 'skipped') then
    raise exception 'invalid_meta_purchase_delivery_status';
  end if;

  update public.meta_purchase_attempts
  set status = p_status,
      meta_response_status = p_meta_response_status
  where order_id = p_order_id
    and event_id = p_event_id
    and status = 'claimed';
end;
$$;

revoke all on function public.claim_meta_purchase_delivery(uuid, text) from public, anon, authenticated;
revoke all on function public.mark_meta_purchase_delivery_sent(uuid, text, integer) from public, anon, authenticated;
revoke all on function public.record_meta_purchase_delivery_result(uuid, text, text, integer) from public, anon, authenticated;

grant execute on function public.claim_meta_purchase_delivery(uuid, text) to service_role;
grant execute on function public.mark_meta_purchase_delivery_sent(uuid, text, integer) to service_role;
grant execute on function public.record_meta_purchase_delivery_result(uuid, text, text, integer) to service_role;
